In [7]:
#import libraries
import numpy as np

In [6]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr)
print("\n Average number:", arr.mean())

[10 20 30 40 50 60 70]

 Average number: 40.0


In [9]:
#indexing
print(arr[3])
print(arr[-2])
print(arr[6])
print(arr[-4])

40
60
70
40


In [10]:
#slicing is a method of assessing value between the index range of that value
print(arr[1:6])
print(arr[6:])
print(arr[:7])
print(arr[-6:-1])
print(arr[7:])
print(arr[-1:-6])

[20 30 40 50 60]
[70]
[10 20 30 40 50 60 70]
[20 30 40 50 60]
[]
[]


In [5]:
#2D indexing and slicing works with the rows and columns
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix[0,1])
print(matrix[1, :])
print(matrix[1:2, 2])
print(matrix[2, :2])
print(matrix[1:2, 0:2])

2
[4 5 6]
[6]
[7 8]
[[4 5]]


In [10]:
#change 1D array to 2D array

arr2 = np.arange(1, 13)
reshape = arr2.reshape(4, 3)

print('Original array', arr2)
print('Reshape array\n', reshape)

# change 2D array to 1D array
flatten = reshape.flatten()
print('Flatten array', flatten)

Original array [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshape array
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Flatten array [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [19]:
#working with basic mathematical operators
arr3 = np.array([1, 2, 3, 4, 5])
arr4 = np.array([10, 20, 30, 40, 50])

#basic operators
print(arr3 + arr4)
print(arr3 - arr4)
print(arr3 * arr4)
print(arr4 / arr3)

#Scaler operator
print(arr4**2)
print(arr4//3)


[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[ 100  400  900 1600 2500]
[ 3  6 10 13 16]


In [22]:
#Dot product is a scalar product done for matrix
matrix_1 = np.array([
    [1, 2],
    [3, 4]
])

matrix_2 = np.array([
    [5, 6],
    [7, 8]
])

dot = np.dot(matrix_1, matrix_2)
print('Dot product\n', dot)

multiply = matrix_1 * matrix_2
print('Multiply\n', multiply)

Dot product
 [[19 22]
 [43 50]]
Multiply
 [[ 5 12]
 [21 32]]
