In [2]:
#import libraries
import numpy as np

In [6]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr)
print("\n Average number:", arr.mean())

[10 20 30 40 50 60 70]

 Average number: 40.0


In [9]:
#indexing
print(arr[3])
print(arr[-2])
print(arr[6])
print(arr[-4])

40
60
70
40


In [10]:
#slicing is a method of assessing value between the index range of that value
print(arr[1:6])
print(arr[6:])
print(arr[:7])
print(arr[-6:-1])
print(arr[7:])
print(arr[-1:-6])

[20 30 40 50 60]
[70]
[10 20 30 40 50 60 70]
[20 30 40 50 60]
[]
[]
